from __future__ import annotations

from pathlib import Path

SNAPSHOT_START = "# --- SNAPSHOT AUTO START ---"
SNAPSHOT_END = "# --- SNAPSHOT AUTO END ---"


def render_mirrorlist(servers: list[str]) -> str:
    return "\n".join(f"Server = {server}" for server in servers) + "\n"


def render_limine_conf(
    *,
    timeout_seconds: int,
    kernel_file: str,
    initramfs_file: str,
    fallback_initramfs_file: str,
    mapper_name: str,
    crypt_uuid: str,
    quiet_args: str,
    fallback_extra_args: str,
    intel_ucode_present: bool,
    extra_lts_block: str,
) -> str:
    ucode_line = "    module_path: boot():/intel-ucode.img\n" if intel_ucode_present else ""
    base_cmdline = (
        f"root=/dev/mapper/{mapper_name} "
        f"rd.luks.name={crypt_uuid}={mapper_name} "
        f"rd.luks.options={crypt_uuid}=discard "
        f"rootflags=subvol=@ rw {quiet_args}"
    ).strip()
    fallback_cmdline = (
        f"root=/dev/mapper/{mapper_name} "
        f"rd.luks.name={crypt_uuid}={mapper_name} "
        f"rd.luks.options={crypt_uuid}=discard "
        f"rootflags=subvol=@ rw {fallback_extra_args}"
    ).strip()
    rescue_cmdline = f"{fallback_cmdline} systemd.unit=emergency.target".strip()

    return (
        "# Limine v10 configuration (UEFI)\n"
        "# Location: /EFI/BOOT/limine.conf (highest priority for EFI-booted Limine)\n\n"
        f"timeout: {timeout_seconds}\n"
        "quiet: no\n"
        "editor_enabled: no\n\n"
        f"/Arch Linux ({kernel_file.replace('vmlinuz-', '')})\n"
        "    protocol: linux\n"
        f"    kernel_path: boot():/{kernel_file}\n"
        f"{ucode_line}"
        f"    module_path: boot():/{initramfs_file}\n"
        f"    cmdline: {base_cmdline}\n\n"
        f"/Arch Linux ({kernel_file.replace('vmlinuz-', '')}, fallback initramfs)\n"
        "    protocol: linux\n"
        f"    kernel_path: boot():/{kernel_file}\n"
        f"{ucode_line}"
        f"    module_path: boot():/{fallback_initramfs_file}\n"
        f"    cmdline: {fallback_cmdline}\n\n"
        "/Arch Linux (rescue)\n"
        "    protocol: linux\n"
        f"    kernel_path: boot():/{kernel_file}\n"
        f"{ucode_line}"
        f"    module_path: boot():/{initramfs_file}\n"
        f"    cmdline: {rescue_cmdline}\n\n"
        f"{extra_lts_block}"
        f"{SNAPSHOT_START}\n"
        "# (Step 08 will replace the block between START/END)\n"
        f"{SNAPSHOT_END}\n"
    )


def render_snapshot_block(
    *,
    kernel_file: str,
    initramfs_file: str,
    mapper_name: str,
    crypt_uuid: str,
    snapshot_ids: list[str],
    quiet_args: str,
    intel_ucode_present: bool,
) -> str:
    if not snapshot_ids:
        return ""

    ucode_lines = ["    module_path: boot():/intel-ucode.img"] if intel_ucode_present else []
    lines = [
        "# Auto-generated snapshot entries (newest-first)",
        "# Generated by legion_installer.runtime",
        "",
    ]
    for snap_id in snapshot_ids:
        cmdline = (
            f"root=/dev/mapper/{mapper_name} "
            f"rd.luks.name={crypt_uuid}={mapper_name} "
            f"rd.luks.options={crypt_uuid}=discard rw {quiet_args} "
            f"rootflags=subvol=@snapshots/{snap_id}/snapshot"
        ).strip()
        lines.extend(
            [
                f"/Arch Linux (snapshot #{snap_id})",
                "    protocol: linux",
                f"    kernel_path: boot():/{kernel_file}",
                *ucode_lines,
                f"    module_path: boot():/{initramfs_file}",
                f"    cmdline: {cmdline}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def replace_snapshot_block(conf_text: str, block_text: str) -> str:
    block_text = block_text.rstrip()
    if SNAPSHOT_START in conf_text and SNAPSHOT_END in conf_text:
        prefix, rest = conf_text.split(SNAPSHOT_START, 1)
        _, suffix = rest.split(SNAPSHOT_END, 1)
        middle = f"{SNAPSHOT_START}\n{block_text}\n{SNAPSHOT_END}" if block_text else f"{SNAPSHOT_START}\n{SNAPSHOT_END}"
        return f"{prefix}{middle}{suffix}"
    appended = (
        f"\n\n{SNAPSHOT_START}\n{block_text}\n{SNAPSHOT_END}\n"
        if block_text
        else f"\n\n{SNAPSHOT_START}\n{SNAPSHOT_END}\n"
    )
    return conf_text.rstrip() + appended


def enable_pacman_option(pacman_conf_text: str, option: str) -> str:
    return pacman_conf_text.replace(f"#{option}", option)


def set_mkinitcpio_var(text: str, key: str, value: str) -> str:
    lines = text.splitlines()
    replaced = False
    for index, line in enumerate(lines):
        if line.strip().startswith(f"{key}="):
            lines[index] = f"{key}={value}"
            replaced = True
            break
    if not replaced:
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def ensure_multilib_enabled(pacman_conf_text: str) -> str:
    if "[multilib]" in pacman_conf_text:
        return pacman_conf_text
    old = "#[multilib]\n#Include = /etc/pacman.d/mirrorlist"
    new = "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
    return pacman_conf_text.replace(old, new)


def find_first_existing(boot_dir: Path, *candidates: str) -> str | None:
    for candidate in candidates:
        if (boot_dir / candidate).is_file():
            return candidate
    return None
